name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.2.98+167

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_route: ^9.3.0+1
  better_open_file: ^3.6.5
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  country_codes: ^3.1.0+2
  csv: ^6.0.0
  data_table_2: ^2.5.12
  device_info_plus: ^11.3.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  drift: ^2.24.0
  fl_chart: ^0.71.0
  flash: ^3.1.1
  flex_color_scheme: ^8.1.1
  flutter_archive: ^6.0.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^10.0.1
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.7.0
  form_builder_extra_fields: ^12.0.0
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.4.4
  geolocator: ^14.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_mlkit_entity_extraction: ^0.15.1
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  map_launcher: ^3.5.0
  material_design_icons_flutter: ^7.0.7296
  money2: ^6.0.0
  package_info_plus: ^8.2.0
  path_provider: ^2.1.5
  path: ^1.9.0
  reactive_forms: ^18.0.0
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  sentry_flutter: ^8.14.2
  sqlite3_flutter_libs: ^0.5.29+1
  syncfusion_flutter_pdf: ^29.1.37
  syncfusion_flutter_pdfviewer: ^29.1.37
  upgrader: ^11.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  riverpod_mutations_annotation: ^1.0.4
  riverpod_mutations: ^1.2.0
  gap: ^3.0.1

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  dependency_validator: ^4.0.0
  drift_dev: ^2.24.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.3
  riverpod_mutations_generator: ^1.0.9

dependency_overrides:
  better_open_file:
    git:
      url: https://github.com/AndreLuizNogueira/better_open_file.git
      ref: master

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter-jbm-nikel-mobile
  org: nikel-consultores-sl
