name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.2.106+175

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_route: ^10.1.2
  better_open_file: ^3.6.5
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  country_codes: ^3.3.0
  csv: ^6.0.0
  data_table_2: ^2.6.0
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  dotted_border: ^3.1.0
  drift: ^2.27.0
  fl_chart: ^1.0.0
  flash: ^3.1.1
  flex_color_scheme: ^8.3.0
  flutter_archive: ^6.0.3
  flutter_dotenv: ^6.0.0
  flutter_form_builder: ^10.2.0
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.10.0
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  google_mlkit_entity_extraction: ^0.15.1
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.6.1
  map_launcher: ^4.4.0
  material_design_icons_flutter: ^7.0.7296
  money2: ^6.0.5
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  path: ^1.9.1
  reactive_forms: ^18.1.1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.1.0
  shimmer: ^3.0.0
  sentry_flutter: ^9.6.0
  sqlite3_flutter_libs: ^0.5.39
  syncfusion_flutter_pdf: ^30.2.7
  syncfusion_flutter_pdfviewer: ^30.2.7
  upgrader: ^11.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  riverpod_mutations: ^1.2.0
  gap: ^3.0.1

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  built_value_generator: ^8.10.1
  dependency_validator: ^5.0.2
  drift_dev: ^2.27.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.5
  intl_utils: ^2.8.7

dependency_overrides:
  better_open_file:
    git:
      url: https://github.com/AndreLuizNogueira/better_open_file.git
      ref: master

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter-jbm-nikel-mobile
  org: nikel-consultores-sl
