name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_riverpod: ^2.0.0-dev.9
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  jwt_decoder: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  intl: ^0.17.0
  drift: ^2.1.0
  logging: ^1.0.2
  uuid: ^3.0.6
  money2: ^3.1.2
  sqlite3_flutter_libs: ^0.5.9
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  shimmer: ^2.0.0
  flash: ^2.0.3+3
  go_router: ^4.3.0
  material_design_icons_flutter: ^5.0.6996
  flutter_secure_storage: ^6.0.0
  reactive_forms: ^14.1.0
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.3.0
  font_awesome_flutter: ^10.1.0
  open_file: ^3.2.1
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  google_fonts: ^3.0.1
  material_color_utilities:
  dynamic_color: ^1.5.4
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  drift_dev: ^2.1.0
  built_value_generator: ^8.4.1

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "dev_assets/icons/celo-instaladores.png"
#   adaptive_icon_background: "#000000"
#   adaptive_icon_foreground: "dev_assets/icons/celo-instaladores.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true
