name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.0.28+51

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ^3.3.8

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  archive: ^3.3.4
  auto_route: ^5.0.0
  better_open_file: ^3.6.0
  cached_network_image: ^3.2.0
  dio: ^4.0.6
  drift: ^2.0.0
  dynamic_color: ^1.5.4
  fl_chart: ^0.55.2
  flash: ^2.0.5
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^7.7.0
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.2.0
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.2.0
  data_table_2: ^2.3.8
  geolocator: ^9.0.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.0
  logger: ^1.1.0
  map_launcher: ^2.4.0
  material_color_utilities:
  material_design_icons_flutter: ^6.0.7096
  money2: ^3.3.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.0
  path: ^1.8.0
  reactive_forms: ^14.1.0
  riverpod_annotation: ^1.0.6
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.0
  build_runner: ^2.3.0
  built_value_generator: ^8.0.0
  dependency_validator: ^3.2.0
  drift_dev: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.0
  riverpod_generator: ^1.0.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true
