name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.2.88+157

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  better_open_file: ^3.6.5
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  country_codes: ^3.1.0+2
  csv: ^6.0.0
  data_table_2: ^2.5.12
  device_info_plus: ^10.1.2
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  drift: ^2.17.0
  fl_chart: ^0.69.0
  flash: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter_archive: ^6.0.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.5.0
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  form_builder_extra_fields: ^11.0.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_mlkit_entity_extraction: ^0.13.1
  google_mlkit_text_recognition: ^0.13.1
  image: ^4.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.2.0
  map_launcher: ^3.3.0
  material_design_icons_flutter: ^7.0.7296
  money2: ^5.0.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  reactive_forms: ^17.0.1
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.21
  syncfusion_flutter_pdf: ^27.1.48
  syncfusion_flutter_pdfviewer: ^27.1.48
  upgrader: ^11.1.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  riverpod_mutations_annotation: ^1.0.4
  riverpod_mutations: ^1.2.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  dependency_validator: ^4.0.0
  drift_dev: ^2.17.0
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.3
  riverpod_mutations_generator: ^1.0.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true
