name: jbm_nikel_mobile
description: JBM Nikel Mobile
publish_to: "none"
version: 1.2.67+136

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ^3.19.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  archive: ^3.4.10
  auto_route: ^7.8.4
  better_open_file: ^3.6.5
  cached_network_image: ^3.3.1
  dio: ^4.0.6
  drift: ^2.15.0
  dynamic_color: ^1.6.9
  fl_chart: ^0.66.2
  flash: ^3.1.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.1
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  data_table_2: ^2.5.10
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  map_launcher: ^3.3.0
  material_color_utilities:
  material_design_icons_flutter: ^6.0.7296
  money2: ^3.4.1
  package_info_plus: ^6.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  reactive_forms: ^16.1.1
  riverpod_annotation: ^2.3.4
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.20
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  country_codes: ^2.2.0
  csv: ^5.1.1
  share_plus: ^8.0.3
  syncfusion_flutter_pdfviewer: ^24.2.7
  syncfusion_flutter_pdf: ^24.2.7
  flutter_markdown: ^0.6.19
  badges: ^3.1.2
  flex_color_scheme: ^7.3.1
  go_router: ^11.1.2
  device_info_plus: ^9.1.0
  upgrader: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  dependency_validator: ^3.2.3
  drift_dev: ^2.8.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icons/1x/photokits_app_icon_1024x1024.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_intl:
  enabled: true
