name: jbm_nikel_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  jwt_decoder: ^2.0.1
  path: ^1.8.1
  path_provider: ^2.0.10
  intl: ^0.17.0
  drift: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^1.1.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.0
  freezed: ^2.0.3+1

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "dev_assets/icons/celo-instaladores.png"
#   adaptive_icon_background: "#000000"
#   adaptive_icon_foreground: "dev_assets/icons/celo-instaladores.png"

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
